name:  first-workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-24.04
    steps:
      - name: echo a string
        run: echo "hello-world"
      - name: multiple lines
        run: |
          node -v
          npm -v 
  running-paralell-jobs:
    runs-on:  macos-latest
    steps:
      - name: running macos commands
        run: sw-vers  
    
